"""API schemas (OpenAPI contract generated by FastAPI)."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from terraformation.models import Graph, Instance, Output, StateDiff

LockStatus = Literal["locked", "released", "none_detected"]


class LockOut(BaseModel):
    status: LockStatus = Field(description="locked | released | none_detected (a .tflock was never seen)")
    who: str = ""
    operation: str = ""
    lock_id: str = ""
    since: str | None = Field(default=None, description="Start of the active lock (Created of the .tflock)")
    released_at: str | None = None
    duration_s: int | None = Field(default=None, description="Seconds locked so far")
    alert: bool = Field(default=False, description="Lock held longer than the configured threshold")


class ProjectOut(BaseModel):
    project: str
    workspace: str
    path: str = "terraform.tfstate"
    last_modified: str | None = None
    serial: int | None = None
    terraform_version: str | None = None
    lineage: str | None = None
    resource_count: int = 0
    version_count: int = 0
    current_version_id: str | None = None
    deleted: bool = False
    lock: LockOut
    activity: list[int] = Field(default_factory=list, description="Versions per day, last 14 days")
    by_type: dict[str, int] = Field(default_factory=dict)
    by_provider: dict[str, int] = Field(default_factory=dict)
    by_module: dict[str, int] = Field(default_factory=dict)


class Page(BaseModel):
    cursor: str | None = Field(default=None, description="Opaque cursor for the next page")


class ProjectList(Page):
    items: list[ProjectOut]


class VersionOut(BaseModel):
    version_id: str
    last_modified: str
    kind: Literal["state", "delete_marker"] = "state"
    serial: int = 0
    lineage: str = ""
    terraform_version: str = ""
    resource_count: int = 0
    size: int = 0
    added: int = 0
    removed: int = 0
    modified: int = 0
    parse_error: str | None = None
    is_current: bool = False


class VersionList(Page):
    items: list[VersionOut]


class TimelineEvent(BaseModel):
    type: Literal["version", "delete_marker", "lock_acquired", "lock_released"]
    timestamp: str
    version_id: str | None = None
    serial: int | None = None
    terraform_version: str | None = None
    resource_count: int | None = None
    added: int | None = None
    removed: int | None = None
    modified: int | None = None
    who: str | None = None
    operation: str | None = None
    lock_id: str | None = None
    duration_s: int | None = None


class Timeline(BaseModel):
    items: list[TimelineEvent]


class LockRecord(BaseModel):
    lock_id: str
    who: str
    operation: str
    terraform_version: str = ""
    acquired_at: str
    released_at: str | None = None
    duration_s: int | None = None
    active: bool = False
    alert: bool = False


class LockHistory(BaseModel):
    current: LockOut
    items: list[LockRecord]


class ActiveLock(LockOut):
    project: str
    workspace: str
    path: str = "terraform.tfstate"


class ActiveLocks(BaseModel):
    threshold_minutes: int
    items: list[ActiveLock]


class ModuleOut(BaseModel):
    path: str
    resource_count: int


class StateInfoOut(BaseModel):
    project: str
    workspace: str
    path: str = "terraform.tfstate"
    version_id: str
    last_modified: str
    terraform_version: str
    serial: int
    lineage: str
    resource_count: int
    s3_bucket: str
    s3_key: str


class StateDetail(BaseModel):
    info: StateInfoOut
    outputs: list[Output]
    modules: list[ModuleOut]
    resources: list[Instance]


class SearchHit(BaseModel):
    project: str
    workspace: str
    path: str = "terraform.tfstate"
    address: str
    type: str
    name: str
    module: str
    provider: str
    mode: str
    index: str = ""
    attributes: dict[str, str] = Field(default_factory=dict)


class SearchResult(Page):
    items: list[SearchHit]


class DayActivity(BaseModel):
    day: str
    versions: int = 0
    locks: int = 0


class Dashboard(BaseModel):
    projects: int
    states: int
    resources: int
    versions: int
    locked: int
    lock_alerts: int
    lock_threshold_minutes: int
    by_type: dict[str, int]
    by_provider: dict[str, int]
    by_module: dict[str, int]
    by_project: dict[str, int]
    terraform_versions: dict[str, int]
    providers_in_use: list[str]
    activity: list[DayActivity]
    locks: list[ActiveLock]
    recent: list[ProjectOut]


class Facets(BaseModel):
    resource_types: dict[str, int]
    terraform_versions: dict[str, int]
    providers: dict[str, int]
    projects: list[str]


class DiffSummaryRequest(BaseModel):
    workspace: str = "default"
    path: str = "terraform.tfstate"
    from_version: str
    to_version: str
    language: str = "en"


class DiffSummaryOut(BaseModel):
    summary: str
    model_id: str


class PlanPayload(BaseModel):
    """Same payload as Terraboard (POST /api/plans)."""

    lineage: str
    terraform_version: str = ""
    git_remote: str = ""
    git_commit: str = ""
    ci_url: str = ""
    source: str = ""
    plan_json: dict[str, Any] = Field(default_factory=dict)


class PlanResource(BaseModel):
    address: str
    type: str = ""
    actions: list[str]


class PlanSummary(BaseModel):
    id: str
    lineage: str
    created_at: str
    terraform_version: str = ""
    git_remote: str = ""
    git_commit: str = ""
    ci_url: str = ""
    source: str = ""
    counts: dict[str, int] = Field(default_factory=dict)
    exit_code: int = Field(default=0, description="2 if the plan contains changes, 0 otherwise")


class PlanDetail(PlanSummary):
    resources: list[PlanResource] = Field(default_factory=list)
    outputs: list[PlanResource] = Field(default_factory=list)
    provider_constraints: dict[str, str] = Field(default_factory=dict)
    truncated: bool = False


class PlanList(Page):
    items: list[PlanSummary]


class Problem(BaseModel):
    detail: str


__all__ = [
    "Graph",
    "StateDiff",
]


# ---- AWS resources (Terraform -> AWS map) --------------------------------------------------
class AwsMapStatus(BaseModel):
    state: Literal["ok", "degraded", "unavailable"]
    stale: bool = Field(
        description="The map has gone more than `stale_after_days` without review (warning only)"
    )
    reviewed_at: str | None = None
    stale_after_days: int
    entries: int
    issues: list[str] = Field(default_factory=list)


class AwsComponent(BaseModel):
    address: str
    tf_type: str
    cfn_type: str | None = Field(
        default=None, description="Equivalent CloudFormation type, if the map specifies it"
    )


class AwsResourceOut(BaseModel):
    cfn_type: str
    identity: str
    name: str
    status: Literal["verified", "provisional"]
    primaries: list[AwsComponent]
    components: list[AwsComponent]


class UnmappedOut(BaseModel):
    address: str
    tf_type: str
    module: str = "root"
    reason: str = Field(
        description=(
            "no_rule | non_aws_provider | missing_identity | missing_parent_ref | "
            "orphan_child | ambiguous_parent | invalid_map_entry | map_unavailable"
        )
    )
    detail: str = ""


class AwsCoverage(BaseModel):
    managed_total: int
    mapped: int
    unmapped: int
    percent: float
    aws_resources: int
    unmapped_by_reason: dict[str, int]


class AwsResources(BaseModel):
    map: AwsMapStatus
    coverage: AwsCoverage
    resources: list[AwsResourceOut]
    unmapped: list[UnmappedOut]
    helpers: list[AwsComponent]
    data: list[AwsComponent]


class MapTypeUsage(BaseModel):
    tf_type: str
    count: int = Field(description="Instances of this type across all reviewed states")
    states: int = Field(description="Distinct states where it appears")
    mapped: bool
    reason: str | None = Field(default=None, description="Most frequent 'unmapped' reason (if not mapped)")
    cfn_type: str | None = None
    status: str | None = None


class AwsMapCoverage(BaseModel):
    map: AwsMapStatus
    states_checked: int
    states_total: int
    truncated: bool = Field(description="There are more states than `max_states`: coverage is partial")
    resources: int
    resources_unmapped: int
    types_unmapped: int
    types: list[MapTypeUsage]
